# Generated by Django 4.2.8 on 2023-12-30 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verb",
                    models.CharField(
                        choices=[("buy", "BUY"), ("post", "POST")], max_length=10
                    ),
                ),
                (
                    "noun",
                    models.CharField(
                        choices=[("nft", "NFT"), ("feedback", "FEEDBACK")],
                        max_length=10,
                    ),
                ),
                ("timestamp", models.BigIntegerField()),
                ("properties", models.JSONField()),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
